services:
  real2sim_drake:
    image: real2sim_drake
    container_name: real2sim_drake
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - TERM=xterm-256-color
    volumes:
      - /tmp/.X11-unix:/tml/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      - ./:/root/workspace/
      - /home/$(whoami)/.ssh:/root/.ssh
    tty: true
    stdin_open: true
    network_mode: "host"
    privileged: true
    ulimits:
      rtprio: 70
      rttime: -1
      memlock: 8428281856
    devices:
      - "/dev:/dev"
    command: /bin/bash
